import { SITEPROOF_BRAND } from "../../config/brand";
import { SITEPROOF_OFFER } from "../../config/offer";

export function getLicenseReportFooter() {
  return [
    SITEPROOF_BRAND.tagline,
    SITEPROOF_OFFER.emotionalClose,
    "Generated by SiteProof — jobsite proof organized for customers, inspectors, insurance, and payment.",
  ].join(" ");
}

export function getCustomerProofPacketIntro() {
  return {
    title: "Jobsite Proof Packet",
    subtitle: SITEPROOF_BRAND.tagline,
    summary:
      "This packet organizes job photos, notes, timestamps, and field documentation so completed work is easier to verify, review, approve, and pay.",
  } as const;
}
