export const SITEPROOF_LAUNCH_OFFER = {
  name: "SiteProof Crew License",
  price: "$697",
  priceQualifier: "one-time launch offer",
  primaryCta: "Try SiteProof Free on 3 Jobs",
  secondaryCta: "Start 30-Day Field Trial",
  tagline: "Organized proof. Professional reports. Faster payment.",
  brandLine: "Document the job. Protect the company. Get paid faster.",
  domain: "SiteProof.report",
  trial: {
    jobs: 3,
    days: 30,
    label: "3 free jobs / 30-day field trial",
  },
  licenses: {
    included: 7,
    label: "7 crew/device licenses",
  },
  included: [
    "Offline-first job proof app",
    "Multi-crew job documentation",
    "Photos, notes, and voice notes",
    "GPS/timestamp proof",
    "Job timeline",
    "Before/after proof logs",
    "Customer-ready reports",
    "Office-ready reports",
    "Inspection-ready reports",
    "Change-order proof reports",
    "Dispute/payment-ready reports",
    "Closeout reports",
    "Starter trade proof templates",
    "English + Spanish reports",
    "Local device storage",
    "Self-hosted/on-device mode",
    "1 year of app updates included",
    "1 year Cloud Proof Vault included",
  ],
  cloudVault: {
    includedYears: 1,
    renewalPrice: "$147/year",
    fairUseStorageLimit: "Fair-use storage limit included for active contractor use",
    benefits: [
      "Cloud backup",
      "Restore if phone/tablet is lost",
      "Secure report links",
      "Office/customer access",
      "Cloud job archive",
      "Multi-device proof access",
    ],
  },
  brandedReports: {
    name: "Branded Contractor Pro Reports",
    price: "$297",
    priceQualifier: "one-time",
    benefits: [
      "Company logo",
      "Company colors",
      "Branded cover page",
      "Company contact info",
      "License number",
      "Customer-ready intro text",
      "Warranty/disclaimer language",
      "Payment instruction block",
      "Office/admin footer",
      "Bilingual English/Spanish branded footer",
    ],
  },
  reportAssistant: {
    name: "SiteProof Report Assistant",
    rewardValue: "1 year free",
    benefits: [
      "Clean up voice notes",
      "Summarize job notes",
      "Create customer-ready report text",
      "Create inspection summaries",
      "Detect change-order candidates",
      "Flag missing proof before sending",
      "Turn messy field notes into professional reports",
    ],
    dependencyRule: "Report Assistant is a referral/upsell enhancement, not a dependency for core Pro Report generation.",
  },
  referral: {
    title: "Get Report Assistant Free for 1 Year",
    requiredActivatedReferrals: 5,
    rule: "Refer 5 contractor friends. When each completes their first real SiteProof job Pro Report, we unlock 1 year of SiteProof Report Assistant for your account.",
    paidReferralReward: {
      cash: "$100 cash",
      credit: "$150 SiteProof credit",
      rule: "Active users can earn $100 cash or $150 SiteProof credit when a referred contractor completes a first real job Pro Report and buys SiteProof.",
    },
  },
  coreAccessRules: {
    starterTradeTemplatesIncluded: true,
    proReportsIncluded: true,
    noUpsellGate:
      "Core Pro Report formats and starter Trade Template Packs are included in the base SiteProof Crew License.",
  },
  reportFooter: {
    default: "Prepared with SiteProof.report\nOrganized proof. Professional reports. Faster payment.",
    branded: "Powered by SiteProof.report",
    emailPs:
      "P.S. This proof package was prepared with SiteProof.report - a field proof system for contractors who want organized proof, professional reports, and faster payment.",
  },
} as const;
