export const SITEPROOF_BRAND = {
  appName: "SiteProof",
  tagline: "Document the job. Protect the company. Get paid faster.",
  elevatorPitch:
    "SiteProof is an app for contractors that works even without internet. It helps them take job photos, save notes, prove what work was done, avoid arguments, and get paid faster.",
  shortDescription: "Offline-first proof-of-work app for contractors.",
  valuePromise:
    "Capture jobsite proof fast, stay protected, and get paid with less friction.",
  primaryCTA: "Start Job Proof",
  secondaryCTA: "View Proof Report",
  stormModeBanner: "Fully operational without internet.",
  reportFooter:
    "Generated by SiteProof — jobsite proof organized for customers, inspectors, insurance, and payment.",
  proofLanguage: {
    document: "Document the job.",
    protect: "Protect the company.",
    paid: "Get paid faster.",
  },
} as const;

export type SiteProofBrand = typeof SITEPROOF_BRAND;
