import type { SiteProofLanguage } from '../types/settings';

export const i18n = {
  en: {
    common: {
      english: 'English',
      spanish: 'Spanish',
      save: 'Save',
      saved: 'Saved',
      brandPromise: 'Document the job. Protect your company. Get paid faster.',
    },
    navigation: { dashboard: 'Dashboard', jobs: 'Field Jobs', pilot: 'Pilot', settings: 'Settings' },
    jobs: { startJob: 'Start Job', customerName: 'Customer Name', jobAddress: 'Job Address' },
    capture: { captureLanguage: 'Capture Language', manualFallback: 'Type a note if voice capture is unavailable.' },
    voice: { title: 'Voice Documentation', speakNotes: 'Speak your notes' },
    reports: {
      reportLanguage: 'Report Language',
      spanishReport: 'Spanish Report',
      englishReport: 'English Report',
      audience: 'For customers, inspectors, insurance, and office use',
      reportTitle: 'SiteProof Jobsite Proof Report',
      subtitle: 'Professional Jobsite Documentation',
      customer: 'Customer',
      address: 'Address',
      date: 'Date',
      photoEvidence: 'Photo Evidence',
      voiceNotes: 'Voice Notes',
      materials: 'Materials',
      issues: 'Issues',
      customerRequests: 'Customer Requests',
      changeOrders: 'Change Order Candidates',
      generatedBy: 'Generated by SiteProof',
    },
    settings: { title: 'System Settings', language: 'Language Settings' },
    cloud: {
      title: 'Cloud Backup',
      optional: 'Cloud backup is optional.',
      offlineCore: 'Core job capture and export work offline without cloud.',
      backsUp: 'Cloud can back up jobs, photos, and reports.',
      enabled: 'Cloud backup enabled',
      disabled: 'Cloud backup disabled',
    },
    offline: {
      stormMode: 'Storm Mode: Fully operational without internet.',
      preparing: 'Preparing offline shell',
      queued: 'Cloud sync pending until internet returns.',
    },
    errors: { unavailable: 'Unavailable' },
  },
  es: {
    common: {
      english: 'Inglés',
      spanish: 'Español',
      save: 'Guardar',
      saved: 'Guardado',
      brandPromise: 'Documenta el trabajo. Protege tu empresa. Cobra más rápido.',
    },
    navigation: { dashboard: 'Panel', jobs: 'Trabajos', pilot: 'Piloto', settings: 'Configuración' },
    jobs: { startJob: 'Iniciar trabajo', customerName: 'Nombre del cliente', jobAddress: 'Dirección del trabajo' },
    capture: { captureLanguage: 'Idioma de captura', manualFallback: 'Escribe una nota si la captura de voz no está disponible.' },
    voice: { title: 'Documentación de voz', speakNotes: 'Habla tus notas' },
    reports: {
      reportLanguage: 'Idioma del reporte',
      spanishReport: 'Reporte en Español',
      englishReport: 'Reporte en Inglés',
      audience: 'Para clientes, inspectores, seguros y oficina',
      reportTitle: 'Reporte de Prueba de Obra SiteProof',
      subtitle: 'Documentación Profesional de Obra',
      customer: 'Cliente',
      address: 'Dirección',
      date: 'Fecha',
      photoEvidence: 'Evidencia Fotográfica',
      voiceNotes: 'Notas de Voz',
      materials: 'Materiales',
      issues: 'Problemas',
      customerRequests: 'Solicitudes del Cliente',
      changeOrders: 'Posibles Órdenes de Cambio',
      generatedBy: 'Generado por SiteProof',
    },
    settings: { title: 'Configuración del sistema', language: 'Configuración de idioma' },
    cloud: {
      title: 'Respaldo en la nube',
      optional: 'El respaldo en la nube es opcional.',
      offlineCore: 'La captura y exportación funcionan sin nube.',
      backsUp: 'La nube puede respaldar trabajos, fotos y reportes.',
      enabled: 'Respaldo en la nube activado',
      disabled: 'Respaldo en la nube desactivado',
    },
    offline: {
      stormMode: 'Modo Tormenta: Funciona sin internet.',
      preparing: 'Preparando modo sin conexión',
      queued: 'Sincronización pendiente hasta que vuelva internet.',
    },
    errors: { unavailable: 'No disponible' },
  },
} as const;

export type TranslationKey = string;

export function translate(language: SiteProofLanguage, key: TranslationKey): string {
  const read = (source: unknown): unknown => key.split('.').reduce((value: any, segment) => value?.[segment], source);
  const localized = read(i18n[language]);
  const fallback = read(i18n.en);
  return typeof localized === 'string' ? localized : typeof fallback === 'string' ? fallback : key;
}
